#!/bin/bash

if [ "x$1" = "x" ]
then
    exit 0
fi

export D=/data/chroot/$1
test -d $D || exit 0

export MOUNT="/proc /sys /dev /dev/pts /home /tmp"

test -f $D/proc/cpuinfo && chroot $D /etc/chroot-down

for m in $MOUNT
do
        for t in 1 2 3; do umount -l $D/$m 2>/dev/null ; done
done

