#!/bin/bash

if [ "x$1" = "x" ]
then
    exit 0
fi

export D=/data/chroot/$1
test -d $D || exit 0

export MOUNT="/proc /sys /dev /dev/pts /home /tmp"

chroot-down $1

for m in $MOUNT
do
	mount -o bind $m $D/$m
done

chroot $D /etc/chroot-up

