#!/usr/bin/perl

my ($text, @files) = @ARGV;

@files = grep { -f $_ } @files;

if (!@files || !$text) {
	print "comment-out: bad arguments.\n";
	exit 1;
}

for my $file (@files) {

	open my $f, "<", $file;
	my @lines = <$f>;
	close $f;

	foreach my $line (@lines) {
		$line = "#" . $line if $line =~/$text/;
	}

	open $f, ">", $file;
	print $f join('', @lines);
	close $f;
}
