#!/bin/bash

mv /etc/sysctl.conf /etc/sysctl.conf.1 && \
cat > /etc/sysctl.conf << EOT && \
# disable IPv6 (http://superuser.com/questions/692952/disable-ipv6-on-interface-in-debian-wheezy)

net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1



EOT
cat /etc/sysctl.conf.1 >> /etc/sysctl.conf && \
rm /etc/sysctl.conf.1
