#!/usr/bin/perl

use strict;
use warnings;

my $file = "/etc/init.d/chrome-remote-desktop";

open my $f, "<", $file or die "could not open $file!";
my @content = ();
while (<$f>) {
	chomp;
	if (/chuid/ && /exec/ && !/size/) {
		$_ .= " --size 1280x720";
	}
	$_ .= "\n";
	push @content, $_;
}
close $f;

open $f, ">", $file or die "could not write to $file!";
print $f join("", @content);
close $f;
