#!/bin/bash

# If you get errors like the following one, run this script!
#
##  perl: warning: Setting locale failed.    
##  perl: warning: Please check that your locale settings:
##          LANGUAGE = (unset),
##          LC_ALL = (unset),
##          LANG = "en_US.UTF-8"
##      are supported and installed on your system.
##  perl: warning: Falling back to the standard locale ("C").

sudo locale-gen en_US de_DE

