#!/bin/bash

rm -f $HOME/.local/share/recently-used.xbel
mkdir -p $HOME/.local/share/recently-used.xbel

# http://ubuntuforums.org/showthread.php?t=2000108
sudo aptitude purge zeitgeist zeitgeist-core zeitgeist-datahub python-zeitgeist rhythmbox-plugin-zeitgeist geoclue geoclue-ubuntu-geoip geoip-database whoopsie

