#!/usr/bin/perl

my $TIMEOUT_END = 30;
my $TIMEOUT_INVALID = 30;

my $file = $ARGV[0];
my $secondsbeforeend = $ARGV[1] || 0;
my $lastseek = 0;
my $timeout = $TIMEOUT;

while (1) {
	my $length = `midentify $file 2>&1 | grep ID_LENGTH`;
	$length =~ s/ID_LENGTH=//gm;
	$length =~ s/,.*//gm;
	$length =~ s/\s+//gm;
#	my ($hour, $min, $sec) = split(/[:]/, $length);
#	$length = $sec+60*$min+60*60*$hour;

	print "File: $file\n";
	print "Length: $length\n";
	my $seek = int($length) - 2 - $secondsbeforeend;
	print "Seek to: $seek\n";
	print "\n";
	
	my $is_timeout_end = $seek == $lastseek;
	my $is_timeout_invalid = $seek < 0;
	
	if ($is_timeout_end || $is_timeout_invalid) {
		$timeout++;
		if (($is_timeout_end && $timeout < $TIMEOUT_END) || ($is_timeout_invalid && $timeout < $TIMEOUT_INVALID)) {
			sleep(1);
			next;
		}
		else {
			print "Exit.\n";
			exit 0;
		}
	}

	$timeout = 0;
	system("mplayer -xy 500 -ontop -vo gl -osdlevel 3 -ss $seek $file");
	sleep(1);
}
