#!/bin/bash

export a=$1
shift
export b=$1
shift

(
echo "$a -> $b"
rsync --stats --hard-links --human-readable -azvl --size-only "$a/" "$b/" $* --exclude "*.unison.*"
)| grep -v "sending incremental file list" #| perl -n -e 'print if !/^(sent|(total size))/;'
