#!/bin/bash

if [ `whoami` != root ]; then
    echo $0 $* | sudo su -
    exit 0
fi

if [ "x$1" = "x" ]
then
	echo Usage: $0 USER
	exit 0
fi

export U=$1

cd /root

rm -f btsync_*.tar.gz
if file /bin/bash 2>/dev/null | grep 64-bit >/dev/null
then
	wget http://btsync.s3-website-us-east-1.amazonaws.com/btsync_x64.tar.gz
else
	wget http://btsync.s3-website-us-east-1.amazonaws.com/btsync_i386.tar.gz
fi

killall btsync
killall btsync

mkdir -p /etc/btsync/bin
tar xzvf btsync_*.tar.gz -C /etc/btsync/bin
test -d /root/bin/.sync && mv /root/bin/.sync /etc/btsync/bin
export VIP=$(cat /etc/hosts.d/$(hostname)/ip)
export RIP=$(cat /etc/hosts.d/$(hostname)/ip.real)
cat > /etc/btsync/btsync.conf << EOT
{
  "listening_port" : 48888,
  "check_for_updates" : true,
  "use_upnp" : true,
  "lan_encrypt_data" : false,
  "lan_use_tcp" : true,
  "webui" :
  {
      "listen" : "$VIP:8888"
  }
}
EOT
wget -c http://www.ryde.net/code/bind.c.txt -O /etc/btsync/bind.c
gcc -nostartfiles -fpic -shared /etc/btsync/bind.c -o /etc/btsync/bind.so -ldl -D_GNU_SOURCE
chmod 0755 -R /etc/btsync
chown $U:$U -R /etc/btsync

cat /etc/crontab | grep -v BTSYNC > /tmp/btsync-crontab
test -f /tmp/btsync-crontab && (
	cat /tmp/btsync-crontab
	echo "*/5 * * * * $U nice -n 12 flock -n /etc/btsync/btsync.lock sh -c 'BIND_ADDR=$(cat /etc/hosts.d/$(hostname)/ip.real) LD_PRELOAD=/etc/btsync/bind.so /etc/btsync/bin/btsync --config /etc/btsync/btsync.conf' # BTSYNC"
) > /etc/crontab && chmod 0644 /etc/crontab

ufw allow from 192.168.100.0/24 to any port 8888 # btsync webui
ufw allow in on eth0 to any port 48888 # btsync
ufw allow in on eth1 to any port 48888 # btsync

ufw allow in on eth0 to any port 48887 # btsync, alternative port
ufw allow in on eth1 to any port 48887 # btsync, alternative port
