#!/bin/bash

cd $(dirname $0)
export P=$(pwd)

for pkg in autofs sshfs
do
    dpkg -l | grep " $pkg " >/dev/null 2>&1 || aptitude install $pkg
done

mkdir -p /data/storage

echo -n > /etc/auto.master
for basedir in "" $(for y in /data/chroot/*; do echo $y | grep -v '/data/chroot/\*' ; done)
do

	export USERS=$(cd $basedir/home; echo *)
	export HOSTS=$(cd /etc/hosts.d/; echo *)

	for u in $USERS
	do
		echo $basedir"/home/"$u"/remote /etc/auto.sshfs."$u" --timeout=30 --ghost --verbose" >> /etc/auto.master
		echo -n > /etc/auto.sshfs.$u

		for h in $HOSTS
		do
			for d in lan wan
			do
				grep ssh:2200 /etc/hosts.d/$h/services.$d >/dev/null 2>&1 && \
					echo $h"."$d" -fstype=fuse,rw,nodev,nonempty,noatime,allow_other,reconnect,max_read=65536 :sshfs\#root@"$h"."$d"\:/home/"$u >> /etc/auto.sshfs.$u
			done
		done
	done
done

service autofs restart

