#!/bin/bash

cd $(dirname $0)
export P=$(pwd)

for pkg in build-essential liblzo2-dev texinfo libncurses5-dev libreadline-dev zlib1g-dev libssl-dev
do
	dpkg -l | grep " $pkg " >/dev/null 2>&1 || aptitude install $pkg
done

cd

test -f tinc-1.1pre5.tar.gz || (
	wget http://www.tinc-vpn.org/packages/tinc-1.1pre5.tar.gz
	tar xzvf tinc-1.1pre5.tar.gz
)

cd tinc-1.1pre5

make clean
./configure --prefix=/ --exec-prefix=/usr
make
make install

rsync -av $P/tinc-extras/ /

service tinc restart
