#!/bin/bash

ufw disable
ufw logging on
ufw default deny
ufw allow proto tcp from 192.168.100.0/24 to any port 2200 # ssh
ufw allow proto tcp from 192.168.100.0/24 to any port 80 # http
ufw allow proto tcp from 192.168.100.0/24 to any port 443 # https
ufw allow proto tcp from 192.168.100.0/24 to any port 8001 # lighttpd
ufw allow from 192.168.100.0/24 to any port 53 # dns
ufw enable

