#!/bin/bash

ufw allow 111   # portmapper
ufw allow 24007 # Gluster Daemon
ufw allow 24008 # Infiniband management
ufw allow 24009 # Bricks...
ufw allow 24010
ufw allow 24011
ufw allow 24012
ufw allow 24013
ufw allow 24014
ufw allow 24015
ufw allow 24016
ufw allow 24017
ufw allow 24018
ufw allow 24019
ufw allow 24020
ufw allow 34865 # inline Gluster NFS server
ufw allow 34866
ufw allow 34867
