#!/bin/bash
### BEGIN INIT INFO
# Provides:       update-motd
# Required-Start: $network $remote_fs $syslog tinc
# Required-Stop:  $network $remote_fs $syslog
# Default-Start:  2 3 4 5
# Default-Stop:   0 1 6
# Description:    Update MOTD Script
### END INIT INFO

#uname -snrvm > /var/run/motd
(for x in /etc/update-motd.d/*; do bash $x ; done) \
	| grep -v landscape.canonical.com \
	>> /etc/motd.local.new
[ -f /etc/motd.tail ] && cat /etc/motd.tail >> /etc/motd.local.new
mv /etc/motd.local.new /etc/motd.local

exit 0
