#!/bin/bash

. /etc/environment

cd /var/spool/hosts/

tinc-graph tinc.png

(
	cat /etc/motd.local
	echo "TINCPNG"
	echo
	sensors
) | aha --title $(hostname) \
	| sed 's@TINCPNG@<img src="tinc.png" />@gm' \
	> index.html

