#!/bin/sh

set -e

if [ "$IF_TINC_NET" ] ; then
	EXTRA=""
	[ -n "$IF_TINC_PIDFILE" ] && EXTRA="--pidfile=$IF_TINC_PIDFILE" || IF_TINC_PIDFILE=/var/run/tinc.$IF_TINC_NET.pid
	tincd -n "$IF_TINC_NET" -k $EXTRA
	sleep 0.1
	i=0;
	while [ -f "$IF_TINC_PIDFILE" ] ; do
		if [ $i = '30' ] ; then
			echo 'Failed to stop tinc daemon!'
			exit 1
		fi
		sleep 0.1
		i=$(($i+1))
	done
fi

exit 0
